### ISSUE TITLE
issue 1

### ISSUE THREAD

**Issue by dominikaFric** [wdfeww/ProjectSovy#1]
Rename type to description, estimates to turnovers

**Comment by domiNik4** [comment]
remove arrows from input fields,
display warning messages under input fields
lowest input amount allowed: 1euro, 10e2 should be wrong input

**Comment by domiNik4** [comment]
remove horizontal scrollbar caused by long table input

**Comment by domiNik4** [comment]
separate presentation and data (layered architecture)
separate js and css
method names should be verbs doSomething()

**Comment by martinpach** [comment]
Prepisem to...idem uz tie formulare dat do jquery
